[package]
name = "pumpkin-data"
version.workspace = true
edition.workspace = true
build = "build/build.rs"

[build-dependencies]
serde.workspace = true
serde_json.workspace = true

proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"